In [2]:
#Importações
import numpy as np

# Basics

In [3]:
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [4]:
#Somando todos os elementos
vector + 2

array([3, 4, 5, 6])

In [5]:
vector = np.array([[1,2],[3,4]])
vector

array([[1, 2],
       [3, 4]])

In [6]:
#Dimensão
vector.shape

(2, 2)

In [7]:
#Transpostas
vector.T

array([[1, 3],
       [2, 4]])

In [8]:
#Array Diagonal 3x4
np.diag([3,4])

array([[3, 0],
       [0, 4]])

In [9]:
#Dimensões
vector.ndim

2

# Fancy Indexing

In [10]:
a = np.arange(0,10)
mask = (a % 3 == 0) #True for all numbers divisors by 3
extract_from_a = a[mask]
extract_from_a

array([0, 3, 6, 9])

In [11]:
a[a%3 == 0] = -1
a

array([-1,  1,  2, -1,  4,  5, -1,  7,  8, -1])

# Multiplicações de Matrizes

In [38]:
a = np.ones((4,4))
b = np.array([[4., 5., 6., 7.5],
       [7., 0., 5., 6.5],
       [1., 0., 5., 5.],
       [6., 8., 0., 0.]])

a * b, não vai multiplicar as matrizes, mas sim elemento por elemento

In [39]:
a * b 

array([[4. , 5. , 6. , 7.5],
       [7. , 0. , 5. , 6.5],
       [1. , 0. , 5. , 5. ],
       [6. , 8. , 0. , 0. ]])

Para fazer a multiplicação das matrizer...

In [40]:
a.dot(b)

array([[18., 13., 16., 19.],
       [18., 13., 16., 19.],
       [18., 13., 16., 19.],
       [18., 13., 16., 19.]])